### ISSUE TITLE
Bug: Dockerfile's hardcoded CMD disables config of "upstream" and "http-address"

### ISSUE THREAD

**Issue by maglub** [bitnami/bitnami-docker-oauth2-proxy#21]
**Description**

The entrypoint/cmd in the `Dockerfile` effectively overrides any configuration done with environment variables:

`debian-10/Dockerfile`:

```Dockerfile
ENTRYPOINT [ "oauth2-proxy" ]
CMD [ "--upstream=http://0.0.0.0:8080/", "--http-address=0.0.0.0:4180" ]
```

E.g, one cannot change the listening port, nor change the upstream in a `docker-compose.yml` file, since the command line options takes precedence over configuration files and environment variables.

Example of upstream and address:

```yaml
...
      environment:
      ...
        - OAUTH2_PROXY_UPSTREAMS=http://web/
        - OAUTH2_PROXY_HTTP_ADDRESS=0.0.0.0:4180
```

The `Dockerfile` in the oauth2proxy project does not set "CMD" in their `Dockerfile`: https://github.com/oauth2-proxy/oauth2-proxy/blob/master/Dockerfile

**Steps to reproduce the issue:**

1. Set up an application

```yaml
services:
    web:
        image: nginx:latest
        ports:
            - "8081:80"
        volumes:
            - ./docker/nginx.conf:/etc/nginx/nginx.conf
    keycloak:
      image: quay.io/keycloak/keycloak:latest
      environment:
        - KEYCLOAK_USER=admin
        - KEYCLOAK_PASSWORD=admin
        - KEYCLOAK_IMPORT=/tmp/test.json
      volumes:
        - ./test.json:/tmp/test.json
      ports:
        - "8080:8080"
    oauth2proxy:
      image: bitnami/oauth2-proxy
      ports:
        - "4180:4180"
      environment:
        - OAUTH2_PROXY_PROVIDER=oidc
        - OAUTH2_PROXY_CLIENT_ID=test
        - OAUTH2_PROXY_CLIENT_SECRET=AABBCCAABBDDAAEE
        - OAUTH2_PROXY_COOKIE_NAME=MagnusTest
        - OAUTH2_PROXY_COOKIE_SECRET=MGY4K3NMNUJCZ3RrbVhGWSt5UUoydz09
        - OAUTH2_PROXY_COOKIE_SECURE=true
        - OAUTH2_PROXY_EMAIL_DOMAINS=*
        - OAUTH2_PROXY_REDIRECT_URL=http://localhost:4180/oauth2/callback
        - OAUTH2_PROXY_OIDC_ISSUER_URL=http://keycloak:8080/auth/realms/test
        - OAUTH2_PROXY_OIDC_ALLOW_UNVERIFIED_EMAIL=true
        - OAUTH2_PROXY_OIDC_EMAIL_CLAIM=sub
        - OAUTH2_PROXY_CLIENT_SECRET=zpayGC3nWpXRh2E5WBpWatJlObgnIGcd
        - OAUTH2_PROXY_PROVIDER_DISPLAY_NAME=Testing testing
        - OAUTH2_PROXY_SCOPE=email profile openid
        - OAUTH2_PROXY_UPSTREAMS=http://web/
        - OAUTH2_PROXY_HTTP_ADDRESS=0.0.0.0:4180
```

3. [and so on...]

Start the docker container, expecting the upstream to be `http://web:80`

```
(venv) [maglub@Magnuss-MBP-2:~/dev/kmg/admin-gui (master)]$ docker-compose up oauth2proxy
Recreating admin-gui_oauth2proxy_1 ... done
Attaching to admin-gui_oauth2proxy_1
oauth2proxy_1  | [2021/12/25 11:34:03] [proxy.go:89] mapping path "/" => upstream "http://0.0.0.0:8080/"
oauth2proxy_1  | [2021/12/25 11:34:03] [oauthproxy.go:148] OAuthProxy configured for OpenID Connect Client ID: test
oauth2proxy_1  | [2021/12/25 11:34:03] [oauthproxy.go:154] Cookie settings: name:MagnusTest secure(https):true httponly:true expiry:168h0m0s domains: path:/ samesite: refresh:disabled
```

**Describe the results you expected:**

I expected the mapping path "/" to be my configured `http://web/`, which I can workaround by overriding the `CMD` options in my `docker-compose.yml` file, by either setting the `--upstream` and `--http-address`, or by just setting anything (like `--request-logging`, so that the `oauth2-proxy` binary is started with only that option. Another workaround is to use the oauth2proxy's official docker image `quay.io/oauth2-proxy/oauth2-proxy`.

```yaml
    oauth2proxy:
      image: bitnami/oauth2-proxy
      ports:
        - "4180:4180"
      command: --request-logging
...
```

Without override, checking the processes in the container:

```
I have no name!@3d436be1fd9e:/opt/bitnami/oauth2-proxy$ ps -efl
F S UID          PID    PPID  C PRI  NI ADDR SZ WCHAN  STIME TTY          TIME CMD
4 S 1001           1       0  0  80   0 - 179481 -     11:37 ?        00:00:00 oauth2-proxy --upstream=http://0.0.0.0:8080/ --http-address=0.0.0.0:4180
4 S 1001          16       0  1  80   0 -   968 -      11:37 pts/0    00:00:00 bash
4 R 1001          24      16  0  80   0 -  1911 -      11:37 pts/0    00:00:00 ps -efl
```

With the override:

```
I have no name!@d1cae566ddd5:/opt/bitnami/oauth2-proxy$ ps -efl
F S UID          PID    PPID  C PRI  NI ADDR SZ WCHAN  STIME TTY          TIME CMD
4 S 1001           1       0  3  80   0 - 179481 -     11:38 ?        00:00:00 oauth2-proxy --request-logging
4 S 1001          15       0  2  80   0 -   968 -      11:38 pts/0    00:00:00 bash
4 R 1001          23      15  0  80   0 -  1911 -      11:38 pts/0    00:00:00 ps -efl
```

And with the override in place, my environment variables `OAUTH2_PROXY_UPSTREAMS` and `OAUTH2_PROXY_HTTP_ADDRESS` are honoured.

```
(venv) [maglub@Magnuss-MBP-2:~/dev/kmg/admin-gui (master)]$ docker-compose up oauth2proxy
Recreating admin-gui_oauth2proxy_1 ... done
Attaching to admin-gui_oauth2proxy_1
oauth2proxy_1  | [2021/12/25 11:38:35] [proxy.go:89] mapping path "/" => upstream "http://web/"
oauth2proxy_1  | [2021/12/25 11:38:35] [oauthproxy.go:148] OAuthProxy configured for OpenID Connect Client ID: test
oauth2proxy_1  | [2021/12/25 11:38:35] [oauthproxy.go:154] Cookie settings: name:MagnusTest secure(https):true httponly:true expiry:168h0m0s domains: path:/ samesite: refresh:disabled
```

**Version**

- Output of `docker version`:

```
(venv) [maglub@Magnuss-MBP-2:~/dev/kmg/admin-gui (master)]$ docker version
Client:
 Cloud integration: 1.0.17
 Version:           20.10.8
 API version:       1.41
 Go version:        go1.16.6
 Git commit:        3967b7d
 Built:             Fri Jul 30 19:55:20 2021
 OS/Arch:           darwin/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.8
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.16.6
  Git commit:       75249d8
  Built:            Fri Jul 30 19:52:31 2021
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.4.9
  GitCommit:        e25210fe30a0a703442421b0f60afac609f950a3
 runc:
  Version:          1.0.1
  GitCommit:        v1.0.1-0-g4144b63
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

- Output of `docker info`:

```
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Build with BuildKit (Docker Inc., v0.6.3)
  compose: Docker Compose (Docker Inc., v2.0.0)
  scan: Docker Scan (Docker Inc., v0.8.0)

Server:
 Containers: 22
  Running: 10
  Paused: 0
  Stopped: 12
 Images: 95
 Server Version: 20.10.8
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: e25210fe30a0a703442421b0f60afac609f950a3
 runc version: v1.0.1-0-g4144b63
 init version: de40ad0
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 5.10.47-linuxkit
 Operating System: Docker Desktop
 OSType: linux
 Architecture: x86_64
 CPUs: 5
 Total Memory: 7.774GiB
 Name: docker-desktop
 ID: DRDA:AX2O:WF5W:O6LM:5HJR:MAMQ:YNDI:IWMF:V3EB:MHUM:5RKI:J3OG
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 HTTP Proxy: http.docker.internal:3128
 HTTPS Proxy: http.docker.internal:3128
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

```

- Output of `docker-compose version` (if applicable):

```
docker-compose version 1.29.2, build unknown
docker-py version: 5.0.0
CPython version: 3.9.7
OpenSSL version: OpenSSL 1.1.1l  24 Aug 2021
```

**Additional environment details (AWS, VirtualBox, Docker for MAC, physical, etc.):**

* Running under Docker for Mac
